### ISSUE TITLE
Parsing failure on browscap.php line 27.

### ISSUE THREAD

**Issue by fojac** [slimstat/wp-slimstat#22]
The file vendor/browscap-php/browscap/browscap-php/src/Browscap.php has an irrelevant ? on line 27.
This "?" prevents the Wordpress site from loading. I guess this affected many websites with the automatic update feature enabled...
Removing the plugin made the site charge again.

**Comment by robertoschwald** [comment]
See PR #23

**Comment by slimstat** [comment]
Hi, thank you for pointing this out. That question mark is not a typo in this library, it's a new feature in PHP 7.1 called nullable types:

https://www.php.net/manual/en/migration71.new-features.php

This library I'm using is coming from:

https://github.com/browscap/browscap-php

I'm not sure editing their code is the best approach, because it will be one more thing to track every time they release an update. I'm open to exploring other solutions you might come up with.

**Comment by fojac** [comment]
Thank you for your feedback. I can confirm this leads to an important PHP parsing error, with a critical error in Wordpress and the impossibility to load the website.
The PHP version of my hosting provider is 7.3.32.

**Comment by slimstat** [comment]
Thank you, fojac. I am adding some conditional statements around my code that loads that library. I should be able to push a fix to Github later today. Would you be so kind to test it as soon as it's out?

**Comment by fojac** [comment]
Yes, of course.

**Comment by slimstat** [comment]
Hi, I just pushed the fix to the repo. I did not bump the plugin's version up for now, so that you'll get notified when the fix is released on the WP repo.
